#!/usr/bin/env bash

# Example for a line in a crontab:
# Run "sudo crontab -e" and add the following line:
# Reset fcatalog database daily (And write to log)
# * * * * * /full/path/to/reset_db >> /var/log/fcatalog_reset.log 2>&1

# Reset fcatalog server databases.
# This script deletes all fcatalog databases.

# Abort on failure:
set -e

# Full path of fcatalog server dir. Fill this in:
FCATALOG_DOCKER_PATH=.

# Stop fcatalog docker container:
cd ${FCATALOG_DOCKER_PATH}

./stop_server

# Build initial data container. This line deletes all the current databases
# from the fcatalog server:
./initial_data_cont

# Start the server again:
./start_server

# Unset abort on failure:
set +e
