#! /usr/bin/env bash
### BEGIN INIT INFO
# Provides: fcatalog_docker
# Required-Start: docker networking
# Required-Stop: docker networking
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: FCatalog Docker
# Description: Starts and stops the docker container responsible for fcatalog.
# 
### END INIT INFO

# See 
# http://mobiarch.wordpress.com/2014/05/16/creating-an-init-script-in-ubuntu-14-04/ 
# http://www.thegeekstuff.com/2012/03/lsbinit-script/ 

# Fill in the FCATALOG_DOCKER_DIR to be the path of fcatalog_docker:
FCATALOG_DOCKER_DIR=.

cd $FCATALOG_DOCKER_DIR

case "$1" in
 start)
   sudo $FCATALOG_DOCKER_DIR/start_server.sh
   ;;
 stop)
   sudo $FCATALOG_DOCKER_DIR/stop_server.sh
   ;;
 restart)
   sudo $FCATALOG_DOCKER_DIR/stop_server.sh
   sudo $FCATALOG_DOCKER_DIR/start_server.sh
   ;;
 *)
   echo "Usage: fcatalog_docker {start|stop|restart}" >&2
   exit 3
   ;;
esac
